### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by mariereese** [mariereese/capstone-project#1]
### Tasks

- [x] create react app
- [x] install styled components
- [x] install styleguidist
- [x] Create .gitignore
- [x] Setup github connection
- [x] Create .prettierrc
- [x] Define global styles

### Size
small
