### ISSUE TITLE
create Header

### ISSUE THREAD

**Issue by mariereese** [mariereese/capstone-project#11]
### Tasks

- [x] add Header component
- [x] sytle header with stayled components
- [x] document with styleguidist
- [x] make header dynamic
