### ISSUE TITLE
Add navigation

### ISSUE THREAD

**Issue by mariereese** [mariereese/capstone-project#2]
### Value Statement
As a user 
I want to navigate between the pages
so that I can profit from all the apps' content.

### Description
User can change between the three pages: Dashboard, Add shopped Food and Profile
<img width="317" alt="grafik" src="https://user-images.githubusercontent.com/68663775/99382425-d52f0500-28cc-11eb-9b0c-266d2c1fd004.png">

### Acceptance criteria

- [x] user can change between the three pages
- [x] clicking on an icon will bring user to the selected page
- [x] icon of the current page has another color than the inactive pages

### Tasks

- [x] create feature branch
- [x] Add Footer component
- [x] install react router
- [x] Add React Router to the App
- [x] Add svg icons to the Footer
- [x] fix the position of the navbar to the bottom
- [x] set an active color for the icons
- [x] document footer component with styleguidist

### Size
Medium
