### ISSUE TITLE
Add purchase 

### ISSUE THREAD

**Issue by mariereese** [mariereese/capstone-project#3]
### Value Statement

As a user
I want to add my purchased food to a list in the app
so that I can see my carbon footprint.

### Description

- user can add food from the foodlist to his list of purchased food
- the carbon footprint is calculated and displayed in kg 

<img width="252" alt="grafik" src="https://user-images.githubusercontent.com/68663775/99679587-67294000-2a7c-11eb-8c2b-6c568d7fa2cd.png">

<img width="327" alt="grafik" src="https://user-images.githubusercontent.com/68663775/99679813-a788be00-2a7c-11eb-9bfb-79698f9a3240.png">

### Acceptance Criteria

- [x] User can add sth. to his purchase by clicking on the selected food
- [x] purchase list is updated each time user adds food to his list
- [x] the carbon footpint is calculated and displayed in kg 
- [x] total number updates each time user adds food to his list
- [x] user data is still shown on app reload
- [x] same food cannot be selected twice
- [ ] if food is already selected, it's not selectable in the foodList (lighter grey color)

### Tasks

- [x] create feature branch
- [x] create component SumFootprint
- [x] create component PurchaseList
- [ ] use proptypes
- [x] style all components with styled-components
- [x] document all components with styleguidist
- [x] save SumFootprint in locale storage
- [x] save PurchaseList in locale storage

### Size
large
