### ISSUE TITLE
setup database

### ISSUE THREAD

**Issue by mariereese** [mariereese/capstone-project#4]
### Tasks

- [ ] create mongodb database 

- [ ] setup database structure

- [ ] add data to the database

### Size
small
