### ISSUE TITLE
list of food

### ISSUE THREAD

**Issue by mariereese** [mariereese/capstone-project#5]
### Value Statement
As a user
I want to see a list of all the food 
so that I can select food later

### description

<img width="259" alt="grafik" src="https://user-images.githubusercontent.com/68663775/99677202-bcb01d80-2a79-11eb-88de-77d28169ac74.png">

### acceptance criterea

- [x] user can see a list wich includes each food from the database
- [x] the list is ordered alphabetically

### tasks

- [x] create feature branch
- [x] create json file including the data
- [x] create component FoodList
- [x] style component with styled-components
- [x] document component with styleguidist

### size
small
