### ISSUE TITLE
search for food

### ISSUE THREAD

**Issue by mariereese** [mariereese/capstone-project#6]
### Value Statement
As a user
I want to search for a speacial food 
so that I don't have to scrool through the whole list to select the food I want.

### description

<img width="259" alt="grafik" src="https://user-images.githubusercontent.com/68663775/99677202-bcb01d80-2a79-11eb-88de-77d28169ac74.png">

### acceptance criterea

- [x] user can search for a special food in the food list
- [x] the list is filtered by the letters the user types in the search field

### tasks

- [x] create feature branch
- [x] create component SearchFood
- [x] make SearchFood a controlled component
- [x] style component with styled-components
- [x] document all components with styleguidist

### size
small
