### ISSUE TITLE
select weight of food

### ISSUE THREAD

**Issue by mariereese** [mariereese/capstone-project#7]
### Value statement
As a user
I want to select and change the weight of the food 
so that the footprint is calculated accurately.

### Description
<img width="262" alt="grafik" src="https://user-images.githubusercontent.com/68663775/99808959-ed5b8a00-2b41-11eb-83f8-ec71597a99e8.png">

### Acceptance criteria
- [ ] user can change the weight of food, by clicking on the number on the purchase list
- [ ] the input field only accepts numbers
- [ ] sum of carbon footprint is updated each time the user changes the weight of a list item

### Tasks
- [ ] create feature branch
- [ ] create component WeightInput
- [ ] make WeightInput a controlled component
- [ ] use proptypes
- [ ] style component with styled-components
- [ ] document all components with styleguidist
- [ ] write unit tests

### Size
medium
