### ISSUE TITLE
desktop version

### ISSUE THREAD

**Issue by mariereese** [mariereese/capstone-project#8]
### Value statement
As a desktop-user
I want to have a nice desktop version of the App
so that I have a good user Experience on the desktop too.

### Acceptance criteria
- [ ] App looks good on larger displays 
- [ ] the content is aligned in the center of the page 
- [ ] the content is width is limited to a max width

### Tasks
- [ ] create feature branch
- [ ] add media queries to the css styles
- [ ] document it with styleguidist

### Size
small
